apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  name: core-resource-limits
spec:
  limits:
  - max:
      cpu: "4"
      memory: 1Gi
    min:
      cpu: 200m
      memory: 6Mi
    type: Pod
  - default:
      cpu: 1
      memory: 200Mi
    defaultRequest:
      cpu: 500m
      memory: 100Mi
    max:
      cpu: "4"
      memory: 4Gi
    maxLimitRequestRatio:
      cpu: "20"
    min:
      cpu: 100m
      memory: 4Mi
    type: Container